name: Build ZMK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@v3
    with:
      build_matrix_path: config/build.yaml
      config_path: config
